Validate secrets before attempting a deploy

diff --git a/src/templates/deployWorkflow.yaml b/src/templates/deployWorkflow.yaml
--- a/src/templates/deployWorkflow.yaml
+++ b/src/templates/deployWorkflow.yaml
@@ -25,6 +25,20 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
+      - name: Validate Secrets
+        run: |
+          if
+          [ -z "${{ secrets.CLIENTID }}" ] ||
+          [ -z "${{ secrets.CLIENTSECRET }}" ] ||
+          [ -z "${{ secrets.TECHNICALACCID }}" ] ||
+          [ -z "${{ secrets.TECHNICALACCEMAIL }}" ] ||
+          [ -z "${{ secrets.IMSORGID }}" ] ||
+          [ -z "${{ secrets.ORGID }}" ] ||
+          [ -z "${{ secrets.PROJECTID }}" ] ||
+          [ -z "${{ secrets.WORKSPACEID }}" ]; then
+            echo "Please set all required secrets: CLIENTID, CLIENTSECRET, TECHNICALACCID, TECHNICALACCEMAIL, IMSORGID, ORGID, PROJECTID, WORKSPACEID"
+            exit 1
+          fi
       - name: Setup CLI
         uses: adobe/aio-cli-setup-action@1.3.0
         with:
